# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba9ca9180e7c631007a93661d229654b3807339e61d31162b2aaba18a466673e4bf451b0bbf6ecb4605486590c14dcc18f07f079f9a037ab75e2f7213be5a269

test:
  secret_key_base: 482aae7c7b2c3e89b636001615f446bf7c901dc0a066ab40731b8b68cd01a4e89205664cc3ca445f90fe4bf0cf25d0627fbfe872db5d3be957a9390f76361195

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
